version: '3'

services:
  django:
    build: ./backend
    command:  bash -c "python manage.py migrate && python manage.py runserver"
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    networks:
      fixed_compose_network:
        ipv4_address: 192.168.2.10
  frontend:
    build: ./frontend
    command: "npm start"
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"
    networks:
      fixed_compose_network:
        ipv4_address: 192.168.2.20

volumes:
  node-modules:

networks:
  fixed_compose_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24